### ISSUE TITLE
 ThreadManager 28 - FAIL! Titan was not able to commend target

### ISSUE THREAD

**Issue by Toshibabr** [Marc3842h/Titan#129]
[12:54:09 DEBUG] ThreadManager 1 - Starting commending thread for "[U:1:855707245]" using account "elseasdaa".
[12:54:10 WARNING] ThreadManager 1 - Account is already reporting / commending. Aborting forcefully!
[12:54:10 DEBUG] ThreadManager 1 - Starting commending thread for "[U:1:855707245]" using account "elseasdaa".
[12:54:10 ERROR] ThreadManager 27 - FAIL! Titan was not able to commend target 76561198815972973.
[12:55:26 DEBUG] ThreadManager 1 - Starting commending thread for "[U:1:855707245]" using account "elseasdaa".
[12:55:26 DEBUG] ThreadManager 1 - Starting commending thread for "[U:1:855707245]" using account "WellmadeRoughSeahorse".
[12:55:56 ERROR] ThreadManager 28 - FAIL! Titan was not able to commend target 76561198815972973.

**Comment by woah1337** [comment]
+1

**Comment by dvxrte** [comment]
ThreadManager - The Steam Rate Limit has been reached. Please try again in a few minutes.
18:39:42 [Main] DEBUG GC - ShortExclusiveDinosaur (Unprotected) - Steam Rate Limit has been reached. Please try it again in a few minutes...
18:39:42 [Main] ERROR ThreadManager - The Steam Rate Limit has been reached. Please try again in a few minutes.
18:39:48 [Main] ERROR ThreadManager - The Steam Rate Limit has been reached. Please try again in a few minutes.
18:39:48 [Main] ERROR ThreadManager - The Steam Rate Limit has been reached. Please try again in a few minutes.
18:39:48 [Main] ERROR ThreadManager - FAIL! Titan was not able to commend target 76561198871541488.

trying commends
Got this even with the latest release, have only 9 accounts.

**Comment by Toshibabr** [comment]
[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - Default Quartz.NET properties loaded from embedded resource file
[20:27:40 DEBUG] Quartz.NET Scheduler 1 - TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - Quartz Scheduler v."3.0.7.0" created.
[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - RAMJobStore initialized.
[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler 'DefaultQuartzScheduler' initialized
[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler version: 3.0.7.0
[20:27:40 INFORMATION] Quartz.NET Scheduler 1 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - Default Quartz.NET properties loaded from embedded resource file
[20:29:13 DEBUG] Quartz.NET Scheduler 1 - TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - Quartz Scheduler v."3.0.7.0" created.
[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - RAMJobStore initialized.
[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler 'DefaultQuartzScheduler' initialized
[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler version: 3.0.7.0
[20:29:13 INFORMATION] Quartz.NET Scheduler 1 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[20:29:18 INFORMATION] Quartz.NET Scheduler 1 - Scheduler "DefaultQuartzScheduler_$_NON_CLUSTERED" shutting down.
[20:29:18 INFORMATION] Quartz.NET Scheduler 1 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused.
[20:29:18 DEBUG] Quartz.NET Scheduler 1 - Shutting down threadpool...
[20:29:18 DEBUG] Quartz.NET Scheduler 1 - Shutdown of threadpool complete.
[20:29:18 INFORMATION] Quartz.NET Scheduler 1 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED Shutdown complete.
[20:35:31 INFORMATION] Quartz.NET Scheduler 1 - Default Quartz.NET properties loaded from embedded resource file
[20:35:32 DEBUG] Quartz.NET Scheduler 1 - TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
[20:35:32 INFORMATION] Quartz.NET Scheduler 1 - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
[20:35:32 INFORMATION] Quartz.NET Scheduler 1 - Quartz Scheduler v."3.0.7.0" created.
[20:35:32 INFORMATION] Quartz.NET Scheduler 1 - RAMJobStore initialized.
[20:35:32 INFORMATION] Quartz.NET Scheduler 1 - Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[20:35:32 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler 'DefaultQuartzScheduler' initialized
[20:35:32 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler version: 3.0.7.0
[20:35:32 INFORMATION] Quartz.NET Scheduler 1 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - Default Quartz.NET properties loaded from embedded resource file
[20:35:48 DEBUG] Quartz.NET Scheduler 1 - TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - Quartz Scheduler v."3.0.7.0" created.
[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - RAMJobStore initialized.
[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler 'DefaultQuartzScheduler' initialized
[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - Quartz scheduler version: 3.0.7.0
[20:35:48 INFORMATION] Quartz.NET Scheduler 1 - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.

**Comment by Toshibabr** [comment]
[20:27:41 ERROR] Titan 1 - An error occured.
System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.ComponentModel.TypeConverter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element, Boolean inherit)
   at Eto.Platform.FindHandler(Type type)
   at Eto.Widget..ctor()
   at Titan.UI.SharedResources..ctor() in C:\Users\Automation\Desktop\Titan Builds\Titan\Titan\Titan\UI\SharedResources.cs:line 17
   at Titan.UI.UIManager..ctor() in C:\Users\Automation\Desktop\Titan Builds\Titan\Titan\Titan\UI\UIManager.cs:line 28
   at Titan.Titan.Main(String[] args) in C:\Users\Automation\Desktop\Titan Builds\Titan\Titan\Titan\Titan.cs:line 220

=== Pre-bind state information ===
LOG: DisplayName = System.ComponentModel.TypeConverter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Pc/Desktop/Release/
LOG: Initial PrivatePath = NULL
Calling assembly : Eto, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Pc\Desktop\Release\Titan.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.ComponentModel.TypeConverter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Users/Pc/Desktop/Release/System.ComponentModel.TypeConverter.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

[20:29:14 INFORMATION] Titan 1 - No valid verb has been provided while parsing. Opening UI...

**Comment by Toshibabr** [comment]
[21:00:27 DEBUG] AccountManager 1 - Titan Account Manager initialized on "21:00". (1547679627)
[21:00:27 WARNING] AccountManager 1 - The accounts file at "C:\Users\Pc\Desktop\Release\accounts.json" doesn't exist!
[21:00:27 WARNING] AccountManager 1 - Titan will run in dummy mode and allow you to edit the accounts before using it.
[21:00:27 INFORMATION] AccountManager 1 - Account file has been successfully parsed. 0 accounts have been parsed. Details: [{ Index: 0, Count: 0 }]
[21:00:28 DEBUG] AccountManager 1 - Successfully wrote index file.
[21:00:28 DEBUG] AccountManager 1 - Using index #0 for botting.
[21:01:48 DEBUG] AccountManager 1 - Added account in index #0: Username: "LewdWryViper" / Password: "Hornsterrainmac" / Sentry: False / Enabled: True
[21:02:55 DEBUG] AccountManager 1 - Starting botting using index 0.
[21:02:55 DEBUG] AccountManager 1 - Successfully wrote index file.
[21:02:55 DEBUG] AccountManager 1 - Index #0 has been used. It will be unlocked on "09:02:55". Suggesting index #1 for next botting session.

**Comment by Toshibabr** [comment]
[21:01:48 DEBUG] GC - LewdWryViper (Unprotected) 1 - Successfully initialized account object for "LewdWryViper".
[21:02:59 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (1/5)
[21:03:04 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (2/5)
[21:03:09 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (3/5)
[21:03:14 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (4/5)
[21:03:19 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (5/5)
[21:03:24 DEBUG] GC - LewdWryViper (Unprotected) 29 - Successfully disconnected from Steam.

**Comment by Toshibabr** [comment]
[21:00:27 DEBUG] AccountManager 1 - Titan Account Manager initialized on "21:00". (1547679627)
[21:00:27 WARNING] AccountManager 1 - The accounts file at "C:\Users\Pc\Desktop\Release\accounts.json" doesn't exist!
[21:00:27 WARNING] AccountManager 1 - Titan will run in dummy mode and allow you to edit the accounts before using it.
[21:00:27 INFORMATION] AccountManager 1 - Account file has been successfully parsed. 0 accounts have been parsed. Details: [{ Index: 0, Count: 0 }]
[21:00:28 DEBUG] AccountManager 1 - Successfully wrote index file.
[21:00:28 DEBUG] AccountManager 1 - Using index #0 for botting.
[21:01:48 DEBUG] AccountManager 1 - Added account in index #0: Username: "LewdWryViper" / Password: "0ioujjii909" / Sentry: False / Enabled: True
[21:02:55 DEBUG] AccountManager 1 - Starting botting using index 0.
[21:02:55 DEBUG] AccountManager 1 - Successfully wrote index file.
[21:02:55 DEBUG] AccountManager 1 - Index #0 has been used. It will be unlocked on "09:02:55". Suggesting index #1 for next botting session.

**Comment by Toshibabr** [comment]
[21:02:55 DEBUG] ThreadManager 1 - Starting commending thread for "[U:1:855707245]" using account "LewdWryViper".
[21:03:24 ERROR] ThreadManager 15 - FAIL! Titan was not able to commend target 76561198815972973.

**Comment by Toshibabr** [comment]
[21:01:48 DEBUG] GC - LewdWryViper (Unprotected) 1 - Successfully initialized account object for "LewdWryViper".
[21:02:59 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (1/5)
[21:03:04 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (2/5)
[21:03:09 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (3/5)
[21:03:14 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (4/5)
[21:03:19 DEBUG] GC - LewdWryViper (Unprotected) 29 - Disconnected from Steam. Retrying in 5 seconds... (5/5)
[21:03:24 DEBUG] GC - LewdWryViper (Unprotected) 29 - Successfully disconnected from Steam.

**Comment by Marc3842h** [comment]
@dvxrte You have reached the Steam limit. Please wait until you're no longer rate limited.

@Toshibabr Please consider using one comment instead of three. Your log files don't show exactly anything that may cause this, may I ask what Titan version you are running?

**Comment by odenilsoncosta** [comment]
o commend não está funcionando, quando que vai funcionar normalmente?
