### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by r4nd0wn** [Marc3842h/Titan#149]
## Description

Titan do not start when i fill in all my accounts. If I have a look in the Task manager, the Memory is mostly free, so I do not understand why it throws an out of memory exception

## Reproduction Steps

1. Fill in the accounts.json (like 3000~4000 Accounts)
2. Start Titan

## Errors

```bash
14:54:02 [Main] ERROR Titan - An error occured.
System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(StackCrawlMark& stackMark)
   at System.Threading.Thread.Start(Object parameter)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskFactory.StartNew(Action action, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at Serilog.Sinks.Async.BackgroundWorkerSink..ctor(ILogEventSink pipeline, Int32 bufferCapacity, Boolean blockWhenFull, IAsyncLogEventSinkMonitor monitor)
   at Serilog.LoggerConfigurationAsyncExtensions.<>c__DisplayClass2_0.<Async>b__0(ILogEventSink wrappedSink)
   at Serilog.Configuration.LoggerSinkConfiguration.Wrap(LoggerSinkConfiguration loggerSinkConfiguration, Func`2 wrapSink, Action`1 configureWrappedSink, LogEventLevel restrictedToMinimumLevel, LoggingLevelSwitch levelSwitch)
   at Serilog.LoggerConfigurationAsyncExtensions.Async(LoggerSinkConfiguration loggerSinkConfiguration, Action`1 configure, IAsyncLogEventSinkMonitor monitor, Int32 bufferSize, Boolean blockWhenFull)
   at Titan.Logging.LogCreator.CreateDebugLogger(String name)
   at Titan.Logging.LogCreator.Create(String name)
   at Titan.Account.Impl.UnprotectedAccount..ctor(JsonAccount json)
   at Titan.Managers.AccountManager.ParseAccountFile()
   at Titan.Titan.Main(String[] args)
Press any key to exit Titan...
```

## System Information

**Operating System**: Windows 10 Pro
**Titan version**: newest (I cannot tell the number, bcs Titan wont start, but i compiled it new from source

## [EDIT]
1. It always fails when it is between Index 140 and Index 150
1. Checked it out on linux. It passes the 140 Index mark, but I got another error....

```bash
Unhandled Exception:
System.IO.IOException: Too many open files
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamWriter.CreateFile (System.String path, System.Boolean append, System.Boolean checkHost) [0x0001c] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize, System.Boolean checkHost) [0x00055] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize) [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append) [0x00008] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamWriter..ctor(string,bool)
  at System.IO.File.CreateText (System.String path) [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at Titan.Managers.AccountManager.SaveIndexFile () [0x0006a] in <0599992006fe4de38915939b47e8ad06>:0 
  at Titan.Managers.AccountManager.ParseIndexFile () [0x001b3] in <0599992006fe4de38915939b47e8ad06>:0 
  at Titan.Managers.AccountManager.ParseAccountFile () [0x003c3] in <0599992006fe4de38915939b47e8ad06>:0 
  at Titan.Titan.Main (System.String[] args) [0x00490] in <0599992006fe4de38915939b47e8ad06>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Too many open files
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamWriter.CreateFile (System.String path, System.Boolean append, System.Boolean checkHost) [0x0001c] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize, System.Boolean checkHost) [0x00055] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize) [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter..ctor (System.String path, System.Boolean append) [0x00008] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamWriter..ctor(string,bool)
  at System.IO.File.CreateText (System.String path) [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at Titan.Managers.AccountManager.SaveIndexFile () [0x0006a] in <0599992006fe4de38915939b47e8ad06>:0 
  at Titan.Managers.AccountManager.ParseIndexFile () [0x001b3] in <0599992006fe4de38915939b47e8ad06>:0 
  at Titan.Managers.AccountManager.ParseAccountFile () [0x003c3] in <0599992006fe4de38915939b47e8ad06>:0 
  at Titan.Titan.Main (System.String[] args) [0x00490] in <0599992006fe4de38915939b47e8ad06>:0
```

**Comment by raspbianlike** [comment]
Are you using Titan 32 bit or 64 bit?

**Comment by r4nd0wn** [comment]
How can I check?

**Comment by Marc3842h** [comment]
Hey, how much RAM do you have installed on your system?

**Comment by r4nd0wn** [comment]
on 16GB

**Comment by BenCat07** [comment]
Does the same thing happen when run as Administrator with --admin? if so it's probably some 32-bit only issue, if not it's just too many malloc's (malloc too much on linux at once without admin rights and you'll be denied)

**Comment by r4nd0wn** [comment]
I tried it out on Linux, and there is exactly the same problem with too many files...
`System.IO.IOException: Too many open files`

**Comment by r4nd0wn** [comment]
Is somebody else dealing with big accounts lists? If yes, can you share the experience?
Till now, I use a workaround with running Titan in more instances with different account files.

**Comment by r4nd0wn** [comment]
Ok, because nobody seems to have a solution for this Problem, is there any way to compile a 64 bit Version?

**Comment by cybergodjsp** [comment]
tried with 64bit titan, --admin windows server 2012 r2, plenty of ram still get this error.

**Comment by r4nd0wn** [comment]
okay I got it to work
This issue can be closed now. Thx for the support

**Comment by BenCat07** [comment]
@Marc3842h support 100
